title: ergateの主页
author: ergtae
email: ergate_lee@hotmail.com
description: 这就是一个实验，自己玩玩看

# social links
twitter_username: 没有呢
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
